version: "3.9"

services:
  devopsdb:
    image: dadampavankalyan/mynewapp:dbimage
    ports:
      - "1880:3306"
    

  application:
    image: dadampavankalyan/mynewapp:appimage
    ports:
      - "1881:8080"
    depends_on:
      - "devopsdb"
    


